networks:
  service-net:
    external: false

services:
 rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq-my
   ports:
     - "5672:5672"
     - "15672:15672"
   volumes:
     - rabbitmq_data:/var/lib/rabbitmq
   networks:
     - service-net

volumes:
 rabbitmq_data: