POST http://localhost:3333/api/v1/accounts/create
Content-Type: application/json

{
  "name": "Wesley Ara",
  "email": "wesleyara@teste.com",
  "password": "##AAbb2312"
}

###

POST http://localhost:3333/api/v1/accounts/login
Content-Type: application/json

{
  "email": "wesleyara@teste.com",
  "password": "##AAbb2312"
}

###

GET http://localhost:3333/api/v1/accounts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE4ZGY5N2QyLTcxYzMtNGRlNy05YmI5LThmNjNhOTMwZmI0ZiIsImlhdCI6MTc0MDI0ODg3OCwiZXhwIjoxNzQxMTEyODc4fQ.WAOM6FxPyWm-7ZCmliqiz7uT9SpZaHOKqhgeny3O-rI
